GET /api/v2/projects/br-quiet-sea-285524/endpoints/br-quiet-sea-285524 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer p0ye0rf7npro4fo4ngk37hfz1qqxuvplq1laoyub8fv532lf5prijx2h8a9p610g
Host: console.neon.tech
Body: {}


# GET /api/v2/projects/br-quiet-sea-285524/endpoints/br-quiet-sea-285524 HTTP/1.1
# Accept: application/json
# Authorization: Bearer p0ye0rf7npro4fo4ngk37hfz1qqxuvplq1laoyub8fv532lf5prijx2h8a9p610g
# Host: p0ye0rf7npro4fo4ngk37hfz1qqxuvplq1laoyub8fv532lf5prijx2h8a9p610g

